[workspace]
members = ["pgdb", "pgdb_cli"]

[workspace.package]
version = "0.4.0"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
edition = "2018"
repository = "https://github.com/mbr/pgdb-rs"
documentation = "https://docs.rs/pgdb_cli"
license = "MIT OR Apache-2.0"
