[workspace]
members = ["pgdb", "pgdb_cli"]
resolver = "3"

[workspace.dependencies]
percent-encoding = "2.3.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.27.0"
url = "2.5.8"

[workspace.package]
version = "0.10.1"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
edition = "2024"
repository = "https://github.com/mbr/pgdb-rs"
documentation = "https://docs.rs/pgdb_cli"
license = "MIT OR Apache-2.0"
