[package]
name = "pgdb"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
description = "Creates and runs Postgres databases through Rust in temporary directories, cleaned up on drop"
readme = "README.md"

[dependencies]
hex_fmt = "0.3.0"
percent-encoding = "2.3.2"
process_guard = "0.3.0"
rand = "0.10.2"
tempfile = { workspace = true }
thiserror = "2.0.20"
url = { workspace = true }
which = "8.0.5"
