[package]
name = "pgdb_cli"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
description = "Command-line application to run a Postgres database"
readme = "README.md"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive", "env"] }
libc = "0.2.189"
pgdb = { version = "0.9.0", path = "../pgdb" }
signal-hook = "0.4.4"
tempfile = { workspace = true }
url = { workspace = true }

[[bin]]
name = "pgdb"
path = "src/main.rs"
